[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Clinker=rust-lld",
    "-L../../manylinux2014/usr/lib64",
    "-Clink-arg=--sysroot=../../manylinux2014",
]
